return {
    -- {
    --     "nvim-neotest/neotest",
    --     dependencies = {
    --         "lawrence-laz/neotest-zig",
    --         "rouge8/neotest-rust",
    --
    --         "nvim-neotest/nvim-nio",
    --         "nvim-lua/plenary.nvim",
    --         "antoinemadec/FixCursorHold.nvim",
    --         "nvim-treesitter/nvim-treesitter"
    --     },
    --     keys = {
    --         { "<leader>er", function() require "neotest".run.run() end, desc = "Experience [R]un" },
    --     },
    --     config = function()
    --         require "neotest".setup {
    --             adapters = {
    --                 require("neotest-zig") {
    --                     dap = {
    --                         adapter = "lldb",
    --                     },
    --                 },
    --                 require("neotest-rust") {
    --                     dap_adapter = "lldb",
    --                 },
    --             },
    --         }
    --     end
    -- },
}
